# Generated by Django 5.2.7 on 2025-10-31 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('color', models.IntegerField(choices=[(1, 'White'), (2, 'Black'), (3, 'Brown'), (4, 'Gray'), (5, 'Beige')], verbose_name='Color')),
                ('material', models.IntegerField(choices=[(1, 'Wood'), (2, 'Metal'), (3, 'Glass'), (4, 'Leather'), (5, 'Fabric'), (6, 'Plastic')], verbose_name='Material')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('product_image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image 2')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image 3')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image 4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
